### ISSUE TITLE
Adjust to include imprint

### ISSUE THREAD

**Issue by PVince81** [owncloud/theme-example#1]
Might require min-version 10.0.9 depending how it's implemented.

Also need to beware that the setup page doesn't break.

Blocked by https://github.com/owncloud/core/issues/31741

**Comment by PVince81** [comment]
unblocked. turns out you'd only need to override the footer methods and use the `getImprintUrl()`. no need to override `getImprintUrl()`.

**Comment by VicDeo** [comment]
Closing as implemented
