### ISSUE TITLE
Example Theme 1.0.1 (for 10.0.9)

### ISSUE THREAD

**Issue by PVince81** [owncloud/theme-example#3]
When marking a task as done, please add your name to the task!

### Reason
- Release needed for imprint / footer additions https://github.com/owncloud/theme-example/pull/2

### QA
- [ ] Create release branch
- [ ] Create "$version Testplan"
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Changes in the docs needed?

### Build & Marketplace release

- [ ] Bump version in info.xml
- [ ] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version'
- [ ] Create github tag for '$version'
- [ ] Build and sign tarball from github tag '$version'
- [ ] Upload to marketplace
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Rename QA milestone to '$version'
- [ ] Add a new 'Unreleased' section in CHANGELOG.md
- [ ] Create PR to merge changes back to `master`

### Specifics

- Open tickets before QA can start
- Other specifics for app release

**Comment by DeepDiver1975** [comment]
the example theme is not on the marketplace - people shall just clone this repo if they want to know how the theme works. No release necessary from my pov.

**Comment by PVince81** [comment]
I think @pmaier1 wanted to have it for the ability to try it out.

cc @patrickjahns

**Comment by pmaier1** [comment]
> I think @pmaier1 wanted to have it for the ability to try it out.

@michaelstingl wanted to have it on the MP. From my POV it makes sense to also provide it there. I see the issue with including a signature that won't match anymore if people adjust the theme, yes. But still I think it's a good way to show how easy theming can work (we don't provide any other theme except theme-enterprise which is only available via trial). If there's nothing else speaking against a release, why not just do it?

**Comment by DeepDiver1975** [comment]
to me the example theme is something developers need to build their own theme.
developers work on git level not on marketplace level.
the marketplace holds production ready apps - I see no productive use of the example theme.

releasing an app means: maintain it, test it, qa it, release it, dont forget it on core releases ...... we are already short on resources - we shall focus ... not loose yourselves in small bits and pieces.

**Comment by pmaier1** [comment]
> we shall focus ... not loose yourselves in small bits and pieces.

Yep. I'm ok with that.

**Comment by patrickjahns** [comment]
closing for now - as we agreed not to have a marketplace release.

**Comment by michaelstingl** [comment]
remove from core?

**Comment by michaelstingl** [comment]
oh, answered in https://github.com/owncloud/documentation/issues/4226

**Comment by michaelstingl** [comment]
@pmaier1 should version increase to 1.0.1 after @VicDeo 's changes?
