### ISSUE TITLE
Please add the theme-example to the marketplace as downloadable source

### ISSUE THREAD

**Issue by mmattel** [owncloud/theme-example#6]
The current way to get the theme-example from github is imho doable but not professional.
Is there a reason why it is not on marketplace ?

I stumbled over that because of reading https://github.com/owncloud/documentation/pull/4281 (Added theme example download)

@PVince81, @settermjd, @voroyam

**Comment by PVince81** [comment]
The theme example, if delivered through marketplace, cannot be modified as no one is supposed to touch the source code of apps installed from the marketplace.

See discussion here https://github.com/owncloud/theme-example/issues/3#issuecomment-399983317. It was decided to not have it there.

**Comment by mmattel** [comment]
This is good news !
Beacuse we are just writing the doc how to get it and this is something we need to add for better understanding.
